#pragma once

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "Espressif"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "ESP32-C6 Air Quality Sensor"
// #define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_PIN_CODE 20202021
// #define CHIP_DEVICE_CONFIG_USE_TEST_SETUP_DISCRIMINATOR 0xF00
// #define CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION_STRING "TEST_VERSION"